service: personal-website-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"


functions:
  web:
    handler: handler.web
    events:
      - httpApi:
          path: /
          method: get
